#!/usr/bin/env bash
#
# fetch-models.sh -- download GGUF *headers* as test fixtures.
#
# WHY ONLY THE HEADER
# -------------------
# The GGUF header, the key/value metadata block and the tensor index all sit at
# the very front of the file, before any weights. The header parser in
# :core-model is the only thing these fixtures exercise, and it only ever reads
# that prefix. Fetching 64 KB instead of 4 GB turns a fixture refresh from a
# coffee break into a second, and it keeps the working tree small enough that
# nobody is tempted to commit one.
#
# No GGUF -- not even a truncated one -- is ever committed. .gitignore has
# *.gguf and models/ for exactly this reason, and scripts/check-repo-size.sh
# fails the build if one slips through. These files are downloaded on demand and
# regenerated by re-running this script.
#
# A truncated file is deliberately a *realistic* input: a parser that assumes it
# can read past the tensor index is a parser that will crash on a partially
# downloaded model, which is a real state the download manager can produce.
#
# NETWORK REQUIRED. This script talks to huggingface.co over HTTPS and uses
# Range requests. It has no offline mode and fails loudly if the network, the
# host, or the URL is unavailable.
#
# Language choice: bash. curl and sha256sum with a couple of range requests; a
# PowerShell version would add nothing on Windows because Git Bash ships curl.
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# models/ is gitignored wholesale, so anything under here is safe by
# construction. Verified at runtime below rather than assumed.
OUTPUT_DIR="${REPO_ROOT}/models/test-fixtures/gguf-headers"
BYTES=65536
FORCE=0
PRINT_CHECKSUMS=0

# Fixtures, as "<local name>|<url>".
#
# Both are small, permissively licensed, widely mirrored models. They differ in
# the parts of the format that matter to the parser: architecture string,
# quantisation type, tokeniser metadata layout and tensor count.
FIXTURES=(
    "qwen2.5-0.5b-instruct-q8_0.gguf|https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q8_0.gguf"
    "stories15M-q4_0.gguf|https://huggingface.co/ggml-org/models/resolve/main/tinyllamas/stories15M-q4_0.gguf"
)

# Expected sha256 of the truncated fixture, as "<local name>|<sha256>".
#
# These are the digests of the first PINNED_BYTES bytes, recorded on 2026-07-31
# from two independent downloads that agreed. A mismatch means upstream
# re-published the file or something is rewriting the transfer; either way it is
# worth stopping for, so it is a hard failure.
#
# The pin only applies at exactly PINNED_BYTES. Fetching a different prefix
# produces a different digest, which is not a problem -- the check is skipped
# with a note instead of failing.
#
# To re-pin after a deliberate change: run --print-checksums, satisfy yourself
# the files are genuine (model card, second machine, second network), paste, and
# say why in the commit message.
PINNED_BYTES=65536
EXPECTED_SHA256=(
    "qwen2.5-0.5b-instruct-q8_0.gguf|d80f5b6afbe0912ab839ba20ec5c813d083b42765dfe80ce4ea5054c3b26240a"
    "stories15M-q4_0.gguf|22e81de75bdd61d36acaa1210bd9bb6834c31500fee3f2c7ba51e989c8977b24"
)

usage() {
    cat <<'EOF'
Usage: scripts/fetch-models.sh [options]

Downloads the first N bytes of a few real GGUF files into a gitignored
directory, for the :core-model header-parser tests. Requires network access.

Options:
  --bytes <n>         Bytes to fetch per fixture. Default 65536.
                      Raise it if a model's tensor index does not fit; the
                      parser tests will tell you.
  --output <dir>      Destination. Default models/test-fixtures/gguf-headers
                      (covered by the models/ rule in .gitignore).
  --force             Re-download fixtures that already exist.
  --print-checksums   Print sha256 lines suitable for pasting into the
                      EXPECTED_SHA256 table in this script, then exit.
  -h, --help          This text.

Exit status:
  0  all fixtures present and verified
  1  a download, a magic-number check or a checksum failed
  2  usage or tooling problem
EOF
}

die() {
    printf '\nERROR: %s\n' "$1" >&2
    exit 2
}

fail() {
    printf '\nFAILED: %s\n' "$1" >&2
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --bytes)   [ $# -ge 2 ] || die "--bytes needs a value";  BYTES="$2"; shift 2 ;;
        --bytes=*) BYTES="${1#--bytes=}"; shift ;;
        --output)  [ $# -ge 2 ] || die "--output needs a value"; OUTPUT_DIR="$2"; shift 2 ;;
        --output=*) OUTPUT_DIR="${1#--output=}"; shift ;;
        --force)   FORCE=1; shift ;;
        --print-checksums) PRINT_CHECKSUMS=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; die "Unknown argument: $1" ;;
    esac
done

case "${BYTES}" in
    ''|*[!0-9]*) die "--bytes must be a positive integer, got '${BYTES}'" ;;
esac
[ "${BYTES}" -ge 1024 ] || die "--bytes must be at least 1024; a GGUF header alone is larger than that."

command -v curl >/dev/null 2>&1 || die "curl is required and was not found on PATH."

sha256_of() {
    local file="$1"
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "${file}" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "${file}" | awk '{print $1}'
    elif command -v openssl >/dev/null 2>&1; then
        openssl dgst -sha256 "${file}" | awk '{print $NF}'
    else
        printf ''
    fi
}

expected_for() {
    local name="$1" entry
    # A pin recorded at 64 KB says nothing about a 128 KB prefix.
    if [ "${BYTES}" != "${PINNED_BYTES}" ]; then
        printf ''
        return
    fi
    for entry in "${EXPECTED_SHA256[@]:-}"; do
        [ -n "${entry}" ] || continue
        if [ "${entry%%|*}" = "${name}" ]; then
            printf '%s' "${entry##*|}"
            return
        fi
    done
    printf ''
}

mkdir -p "${OUTPUT_DIR}"

# Hygiene gate: refuse to write model data anywhere git can see it.
if command -v git >/dev/null 2>&1 && git -C "${REPO_ROOT}" rev-parse --git-dir >/dev/null 2>&1; then
    if ! git -C "${REPO_ROOT}" check-ignore --quiet -- "${OUTPUT_DIR}"; then
        die "$(printf '%s is not gitignored.\n\nRefusing to download model data into a tracked path. Either use the default\noutput directory or add a .gitignore rule first. No GGUF is ever committed to\nthis repository.' "${OUTPUT_DIR}")"
    fi
fi

if [ "${PRINT_CHECKSUMS}" -eq 1 ]; then
    printf 'Paste these into the EXPECTED_SHA256 table in scripts/fetch-models.sh:\n\n'
    found=0
    for fixture in "${FIXTURES[@]}"; do
        name="${fixture%%|*}"
        path="${OUTPUT_DIR}/${name}"
        if [ -f "${path}" ]; then
            found=1
            printf '    "%s|%s"\n' "${name}" "$(sha256_of "${path}")"
        fi
    done
    if [ "${found}" -eq 0 ]; then
        printf '    (nothing downloaded yet -- run scripts/fetch-models.sh first)\n'
    fi
    exit 0
fi

printf 'output      : %s\n' "${OUTPUT_DIR}"
printf 'bytes each  : %s\n' "${BYTES}"
printf 'network     : required (huggingface.co, HTTP Range requests)\n\n'

problems=0
last_byte=$((BYTES - 1))

for fixture in "${FIXTURES[@]}"; do
    name="${fixture%%|*}"
    url="${fixture#*|}"
    path="${OUTPUT_DIR}/${name}"

    if [ -f "${path}" ] && [ "${FORCE}" -eq 0 ]; then
        printf '[skip]  %s already present (--force to re-download)\n' "${name}"
    else
        printf '[get]   %s\n        %s\n' "${name}" "${url}"
        temporary="${path}.part"
        rm -f "${temporary}"

        # --fail turns an HTTP error into a non-zero exit instead of a file full
        # of HTML. --location follows the redirect to the CDN, which is where
        # huggingface.co actually serves the bytes from.
        if ! curl --fail --silent --show-error --location \
            --range "0-${last_byte}" \
            --retry 3 --retry-delay 2 --connect-timeout 20 --max-time 300 \
            --output "${temporary}" \
            "${url}"; then
            printf '[FAIL]  %s: download failed.\n' "${name}"
            printf '        Check network access and that the URL still exists:\n          %s\n' "${url}"
            rm -f "${temporary}"
            problems=$((problems + 1))
            continue
        fi

        actual_size="$(wc -c <"${temporary}" | tr -d '[:space:]')"
        if [ "${actual_size}" -gt "${BYTES}" ]; then
            # A server that ignores Range answers 200 with the whole file. On a
            # multi-gigabyte model that is exactly what we must not do.
            rm -f "${temporary}"
            printf '[FAIL]  %s: server ignored the Range request (got %s bytes, asked for %s).\n' \
                "${name}" "${actual_size}" "${BYTES}"
            problems=$((problems + 1))
            continue
        fi
        if [ "${actual_size}" -lt "${BYTES}" ]; then
            printf '        note: got %s bytes, fewer than requested (the whole file is smaller).\n' "${actual_size}"
        fi

        mv -f "${temporary}" "${path}"
    fi

    # Magic number check. Cheap, needs no pinned digest, and catches the two
    # things that actually go wrong: an HTML error page saved as a .gguf, and a
    # URL that now points at a different format.
    magic="$(head -c 4 "${path}" | tr -d '\0')"
    if [ "${magic}" != "GGUF" ]; then
        printf '[FAIL]  %s: first four bytes are %q, expected "GGUF".\n' "${name}" "${magic}"
        printf '        The URL probably returned an error page or a redirect stub. Inspect:\n          %s\n' "${path}"
        problems=$((problems + 1))
        continue
    fi

    digest="$(sha256_of "${path}")"
    expected="$(expected_for "${name}")"

    if [ -z "${digest}" ]; then
        printf '[warn]  %s: no sha256 tool found (sha256sum, shasum or openssl); integrity unverified.\n' "${name}"
    elif [ -z "${expected}" ]; then
        if [ "${BYTES}" != "${PINNED_BYTES}" ]; then
            printf '[ok]    %s  GGUF magic ok, sha256 %s (pin skipped: --bytes is not %s)\n' \
                "${name}" "${digest}" "${PINNED_BYTES}"
        else
            printf '[ok]    %s  GGUF magic ok, sha256 %s (unpinned)\n' "${name}" "${digest}"
        fi
    elif [ "${digest}" = "${expected}" ]; then
        printf '[ok]    %s  GGUF magic ok, sha256 pinned and matching\n' "${name}"
    else
        printf '[FAIL]  %s: sha256 mismatch.\n          expected %s\n          actual   %s\n' \
            "${name}" "${expected}" "${digest}"
        printf '        Upstream re-published the file, --bytes changed, or the transfer was\n'
        printf '        tampered with. Do not update the pin without understanding which.\n'
        problems=$((problems + 1))
    fi
done

printf '\n'

if [ "${problems}" -gt 0 ]; then
    fail "${problems} fixture(s) could not be prepared."
fi

if [ "${#EXPECTED_SHA256[@]}" -eq 0 ]; then
    printf 'NOTE: no checksums are pinned yet. Run --print-checksums and commit the table\n'
    printf '      once you have satisfied yourself the downloads are genuine.\n\n'
fi

printf 'Fixtures ready in %s\n' "${OUTPUT_DIR#${REPO_ROOT}/}"
printf 'They are gitignored and must stay that way.\n'
